version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4584:4566-4584"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
