version: '3.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      - localstacknet

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./sre/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - localstacknet

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./sre/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - localstacknet

networks:
  localstacknet:
