server:
  port: 5001

redis:
  enabled: true
  uri: redis://localhost:6379
  ttl: 3600

aws:
  execution: false
  endpoints:
    dynamodb:
      endpointOverride: http://localhost:4566
  region: us-east-1

amazon:
  dynamodb:
    endpoint: "http://localhost:4566"
  aws:
    accesskey: "accesskey"
    secretkey: "secretkey"

springdoc:
  api-docs:
    path: /api-docs
